#' Read in GDX and calculate variables that need variables produced by other
#' report*.R functions, used in convGDX2MIF.R for the reporting
#'
#' Read in GDX and calculate variables that need variables produced by other report*.R functions
#'
#'
#' @param gdx a GDX as created by readGDX, or the file name of a gdx
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' @param regionSubsetList a list containing regions to create report variables region
#' aggregations. If NULL (default value) only the global region aggregation "GLO" will
#' be created.
#' @param t temporal resolution of the reporting, default:
#' t=c(seq(2005,2060,5),seq(2070,2110,10),2130,2150)
#' @param extraData path to extra data files to be used in the reporting
#'
#' @author Lavinia Baumstark, Falk Benke
#' @examples
#'
#' \dontrun{reportCrossVariables(gdx)}
#'
#' @export
#' @importFrom assertr assert not_na
#' @importFrom gdx readGDX
#' @importFrom magclass getYears getRegions mbind setNames mselect
#' new.magpie setYears mcalc
#' @importFrom tibble as_tibble
#' @importFrom data.table :=
#' @importFrom tidyselect everything
#' @importFrom madrat toolAggregate
#'

reportCrossVariables <- function(gdx, output = NULL, regionSubsetList = NULL,
                                 t = c(seq(2005, 2060, 5), seq(2070, 2110, 10), 2130, 2150),
                                 extraData) {
  if (is.null(output)) {
    stop("please provide a file containing all needed information")
  }

  ## delete "+" and "++" from variable names
  output <- deletePlus(output)

  module2realisation <- readGDX(gdx, "module2realisation", react = "silent")
  rownames(module2realisation) <- module2realisation$modules

  ####### conversion factors ##########
  TWa_2_EJ <- 31.536
  ####### read in needed data #########
  ## sets
  pe2se <- readGDX(gdx, "pe2se")

  ## equations
  sebal.m <- readGDX(gdx, name = c("q_balSe", "q_sebal"), types = "equations", field = "m", format = "first_found")
  demPE <- readGDX(gdx, name = c("vm_demPe", "v_pedem"), field = "l", restore_zeros = FALSE, format = "first_found") * TWa_2_EJ
  demPE <- demPE[pe2se]

  ####### calculate minimal temporal and regional resolution #####
  y <- Reduce(intersect, list(getYears(output), getYears(sebal.m)))
  r <- Reduce(intersect, list(getRegions(output), getRegions(sebal.m)))
  output <- output[, y, ]

  ####### calculate reporting parameters ############
  tmp <- NULL
  tmp <- mbind(tmp,setNames(
    output[r,,"SE|Electricity|Biomass (EJ/yr)"]
    * output[r,,"PE|Biomass|Energy Crops (EJ/yr)"]
    / dimSums(mselect(demPE,all_enty="pebiolc"),dim=3),   "SE|Electricity|Biomass|Energy Crops (EJ/yr)"))
  getSets(tmp) <- c("all_regi", "ttot", "variable")
  tmp <- mbind(tmp,setNames(
    output[r,,"SE|Electricity|Biomass (EJ/yr)"]
    * output[r,,"PE|Biomass|Residues (EJ/yr)"]
    / dimSums(mselect(demPE,all_enty="pebiolc"),dim=3),   "SE|Electricity|Biomass|Residues (EJ/yr)"))
  tmp <- mbind(tmp,setNames(
    output[r,,"SE|Liquids|Biomass|Cellulosic (EJ/yr)"]
    * output[r,,"PE|Biomass|Residues (EJ/yr)"]
    / dimSums(mselect(demPE,all_enty="pebiolc"),dim=3),    "SE|Liquids|Biomass|Cellulosic|++|Residues (EJ/yr)"))
  tmp <- mbind(tmp,setNames(
    output[r,,"SE|Liquids|Biomass|Cellulosic (EJ/yr)"]
    * output[r,,"PE|Biomass|Energy Crops (EJ/yr)"]
    / dimSums(mselect(demPE,all_enty="pebiolc"),dim=3),    "SE|Liquids|Biomass|Cellulosic|++|Energy Crops (EJ/yr)"))


  tmp <- mbind(tmp,setNames(
    output[r,,"Energy Investments (billion US$2017/yr)"]
    -output[r,,"Energy Investments|Electricity (billion US$2017/yr)"],"Energy Investments|Non-Electricity (billion US$2017/yr)"))
  # gas capacity factor
  tmp <- mbind(tmp,setNames(
    output[r,,"SE|Electricity|Gas (EJ/yr)"] / output[r,,"Cap|Electricity|Gas (GW)"] / TWa_2_EJ * 1000 * 100,
    "Capacity Factor|Electricity|Gas (%)"))

  # wind real capacity factor (before curtailment)
  tmp <- mbind(tmp,setNames(
    output[r,,"SE|Electricity|Wind (EJ/yr)"] / output[r,,"Cap|Electricity|Wind (GW)"] / TWa_2_EJ * 1000 * 100,
    "Theoretical Capacity Factor|Electricity|Wind (%)"))

  # wind capacity factor  (with curtailment considered)
  tmp <- mbind(tmp,setNames(
    (output[r,,"SE|Electricity|Wind (EJ/yr)"] - output[r,,"SE|Electricity|Curtailment|Wind (EJ/yr)"]) /
      output[r,,"Cap|Electricity|Wind (GW)"] / TWa_2_EJ * 1000 * 100, "Real Capacity Factor|Electricity|Wind (%)"))

  # solar real capacity factor (before curtailment)
  tmp <- mbind(tmp,setNames(
    output[r,,"SE|Electricity|Solar (EJ/yr)"] / output[r,,"Cap|Electricity|Solar (GW)"] / TWa_2_EJ * 1000 * 100,
    "Theoretical Capacity Factor|Electricity|Solar (%)"))

  # solar capacity factor  (with curtailment considered)
  tmp <- mbind(tmp,setNames(
    (output[r,,"SE|Electricity|Solar (EJ/yr)"] - output[r,,"SE|Electricity|Curtailment|Solar (EJ/yr)"]) /
      output[r,,"Cap|Electricity|Solar (GW)"] / TWa_2_EJ * 1000 * 100, "Real Capacity Factor|Electricity|Solar (%)"))

  # add global values
  tmp <- mbind(tmp,dimSums(tmp,dim=1))
  # add other region aggregations
  if (!is.null(regionSubsetList))
    tmp <- mbind(tmp, calc_regionSubset_sums(tmp, regionSubsetList))

  # correct global values for intensive variables (prices, LCOES, Capacity factors)
  map <- data.frame(region=getRegions(tmp["GLO",,,invert=TRUE]),world="GLO",stringsAsFactors=FALSE)
  varWeights <- c("Capacity Factor|Electricity|Gas (%)" = "Cap|Electricity|Gas (GW)",
                  "Real Capacity Factor|Electricity|Wind (%)" = "Cap|Electricity|Wind (GW)",
                  "Theoretical Capacity Factor|Electricity|Wind (%)" = "Cap|Electricity|Wind (GW)",
                  "Real Capacity Factor|Electricity|Solar (%)" = "Cap|Electricity|Solar (GW)",
                  "Theoretical Capacity Factor|Electricity|Solar (%)" = "Cap|Electricity|Solar (GW)")
  for (var in names(varWeights)) {
    tmp["GLO",,var] <- toolAggregate(tmp[map$region,,var], rel = map, weight = output[map$region,,varWeights[[var]]])
  }


  # correct region aggregated values for intensive variables (prices, LCOES, Capacity factors)
  if (!is.null(regionSubsetList)) {
    for (region in names(regionSubsetList)) {
      map <- data.frame(
        region = regionSubsetList[[region]],
        parentRegion = region,
        stringsAsFactors = FALSE
      )

      for (var in names(varWeights)) {
        tmp[region, , var] <- toolAggregate(
          tmp[regionSubsetList[[region]], , var],
          rel = map,
          weight = output[regionSubsetList[[region]], , varWeights[[var]]],
          zeroWeight = "setNA"
        )
      }
    }
  }

  # variables that are calculated for all regions including GLO in the same way
  tmp <- mbind(
    tmp,

    setNames(
      output[,,"FE (EJ/yr)"] * 1000
      / output[,,"GDP|MER (billion US$2017/yr)"],
      "Intensity|GDP|Final Energy (MJ/US$2017)"),

    setNames(
      output[,,"GDP|MER (billion US$2017/yr)"]
      / output[,,"FE (EJ/yr)"],
      "Productivity|GDP|MER|Final Energy (US$2017/GJ)"),

    setNames(
      output[,,"GDP|PPP (billion US$2017/yr)"]
      / output[,,"FE (EJ/yr)"],
      "Productivity|GDP|PPP|Final Energy (US$2017/GJ)"),

    setNames(
      output[,,"Emi|CO2|Energy and Industrial Processes (Mt CO2/yr)"]
      / output[,,"FE (EJ/yr)"],
      "Intensity|Final Energy|CO2 (Mt CO2/EJ)"),

    setNames(
      output[,,"Emi|GHG (Mt CO2eq/yr)"]
      / output[,,"FE (EJ/yr)"],
      "Intensity|Final Energy|GHG (Mt CO2-equiv/EJ)"),

    setNames(
      output[,,"Emi|GHG (Mt CO2eq/yr)"]
      / output[,,"GDP|MER (billion US$2017/yr)"],
      "Intensity|GDP|GHG (Mt CO2-equiv/US$2017)"),

    setNames(
      output[,,"GDP|MER (billion US$2017/yr)"]
      / output[,,"Population (million)"],
      "GDP|per capita|MER (kUS$2017/per capita)"),

    setNames(
      output[,,"GDP|PPP (billion US$2017/yr)"]
      / output[,,"Population (million)"],
      "GDP|per capita|PPP (kUS$2017/per capita)"),

    setNames(
      output[,,"Welfare|Real and undiscounted|Yearly (arbitrary unit/yr)"]
      / output[,,"Population (million)"],
      "Welfare|per capita|Real and undiscounted|Yearly (arbitrary unit/yr)"),

    setNames(
      output[,,"Emi|CO2|Industrial Processes|Industry|Cement (Mt CO2/yr)"]
      / output[,,"Production|Industry|Cement (Mt/yr)"],
      "Carbon Intensity|Production|Cement|+|Industrial Processes (Mt CO2/Mt)"),

    setNames(
      (  output[,,"Emi|CO2|Energy|Demand|Industry|Cement|Gases|Fossil (Mt CO2/yr)"]
         + output[,,"Emi|CO2|Energy|Demand|Industry|Cement|Liquids|Fossil (Mt CO2/yr)"]
         + output[,,"Emi|CO2|Energy|Demand|Industry|Cement|Solids|Fossil (Mt CO2/yr)"]
      ) / output[,,"Production|Industry|Cement (Mt/yr)"],
      "Carbon Intensity|Production|Cement|+|Fossil|Energy|Demand (Mt CO2/Mt)"),

    setNames(
      (  output[,,"Emi|CO2|Energy|Demand|Industry|Steel|Gases|Fossil (Mt CO2/yr)"]
         + output[,,"Emi|CO2|Energy|Demand|Industry|Steel|Liquids|Fossil (Mt CO2/yr)"]
         + output[,,"Emi|CO2|Energy|Demand|Industry|Steel|Solids|Fossil (Mt CO2/yr)"]
      ) / output[,,"Production|Industry|Steel (Mt/yr)"],
      "Carbon Intensity|Production|Steel|Fossil|Energy|Demand (Mt CO2/Mt)")

  )

  tmp <- mbind(tmp,setNames(
    tmp[,,"Carbon Intensity|Production|Cement|+|Industrial Processes (Mt CO2/Mt)"]
    + tmp[,,"Carbon Intensity|Production|Cement|+|Fossil|Energy|Demand (Mt CO2/Mt)"],
    "Carbon Intensity|Production|Cement (Mt CO2/Mt)"))

  # Energy shares
  tmp <- mbind(
    tmp,
    setNames(
      100
      * ( output[,,"SE|Electricity|Non-Biomass Renewables (EJ/yr)"]
          + output[,,"SE|Electricity|Biomass (EJ/yr)"]
      )
      # "gross electricity demand" is just the sum of electricity generation
      #  plus imports (excluding output from pump hydro storage that has no
      #   natural inflows)
      / ( output[,,"SE|Electricity (EJ/yr)"]
          # default net imports to zero if not present in data
          + dimSums(mselect(tmp, list(variable = 'SE|Electricity|Net Imports (EJ/yr)')),
                    dim = 3)
      ),
      "Secondary Energy|Electricity|Share of renewables in gross demand|Estimation (%)"))

  # Energy expenditures
  tmp <- mbind(tmp,setNames(
    output[,,"FE|Transport|Liquids (EJ/yr)"] * output[,,"Price|Final Energy|Transport|Liquids (US$2017/GJ)"] +
      output[,,"FE|Transport|Hydrogen (EJ/yr)"] * output[,,"Price|Final Energy|Transport|Hydrogen (US$2017/GJ)"] +
      output[,,"FE|Transport|Electricity (EJ/yr)"] * output[,,"Price|Final Energy|Transport|Electricity (US$2017/GJ)"],
    "Expenditure|Transport|Fuel (billion US$2017/yr)"))

  # calculate intensities growth
  int_gr <- new.magpie(getRegions(tmp),getYears(tmp),c("Intensity Growth|GDP|Final Energy (% pa)","Intensity Growth|GDP|Final Energy to 2005 (% pa)",
                                                       "Intensity Growth|GDP|CO2-equiv (% pa)","Intensity Growth|GDP|CO2-equiv to 2005 (% pa)",
                                                       "Intensity Growth|Final Energy|CO2-equiv (% pa)","Intensity Growth|Final Energy|CO2-equiv to 2005 (% pa)",
                                                       "Intensity Growth|Final Energy|CO2 (% pa)","Intensity Growth|Final Energy|CO2 to 2005 (% pa)"),fill=0)
  for (t in getYears(tmp[,which(getYears(tmp,as.integer=TRUE)>2005),])){
    int_gr[,t,"Intensity Growth|GDP|Final Energy (% pa)"] <-
      (
        (
          (tmp[,t,"Intensity|GDP|Final Energy (MJ/US$2017)"] / setYears(tmp[,(which(getYears(tmp)==t)-1),"Intensity|GDP|Final Energy (MJ/US$2017)"],t))
          ^ (1 / ( getYears(tmp[,t,],as.integer=TRUE) - getYears(tmp[,(which(getYears(tmp)==t)-1),],as.integer=TRUE) ) )
        ) - 1
      ) * 100
    int_gr[,t,"Intensity Growth|GDP|Final Energy to 2005 (% pa)"] <-
      (
        (
          (tmp[,t,"Intensity|GDP|Final Energy (MJ/US$2017)"] / setYears(tmp[,2005,"Intensity|GDP|Final Energy (MJ/US$2017)"],t))
          ^ (1 / ( getYears(tmp[,t,],as.integer=TRUE) - 2005 ) )
        ) - 1
      ) * 100
    int_gr[,t,"Intensity Growth|Final Energy|CO2 (% pa)"] <-
      (
        (
          (tmp[,t,"Intensity|Final Energy|CO2 (Mt CO2/EJ)"] / setYears(tmp[,(which(getYears(tmp)==t)-1),"Intensity|Final Energy|CO2 (Mt CO2/EJ)"],t))
          ^ (1 / ( getYears(tmp[,t,],as.integer=TRUE) - getYears(tmp[,(which(getYears(tmp)==t)-1),],as.integer=TRUE) ) )
        ) - 1
      ) * 100
    int_gr[,t,"Intensity Growth|Final Energy|CO2 to 2005 (% pa)"] <-
      (
        (
          (tmp[,t,"Intensity|Final Energy|CO2 (Mt CO2/EJ)"] / setYears(tmp[,2005,"Intensity|Final Energy|CO2 (Mt CO2/EJ)"],t))
          ^ (1 / ( getYears(tmp[,t,],as.integer=TRUE) - 2005 ) )
        ) - 1
      ) * 100
    int_gr[,t,"Intensity Growth|GDP|CO2-equiv (% pa)"] <-
      (
        (
          (tmp[,t,"Intensity|GDP|GHG (Mt CO2-equiv/US$2017)"] / setYears(tmp[,(which(getYears(tmp)==t)-1),"Intensity|GDP|GHG (Mt CO2-equiv/US$2017)"],t))
          ^ (1 / ( getYears(tmp[,t,],as.integer=TRUE) - getYears(tmp[,(which(getYears(tmp)==t)-1),],as.integer=TRUE) ) )
        ) - 1
      ) * 100
    int_gr[,t,"Intensity Growth|GDP|CO2-equiv to 2005 (% pa)"] <-
      (
        (
          (tmp[,t,"Intensity|GDP|GHG (Mt CO2-equiv/US$2017)"] / setYears(tmp[,2005,"Intensity|GDP|GHG (Mt CO2-equiv/US$2017)"],t))
          ^ (1 / ( getYears(tmp[,t,],as.integer=TRUE) - 2005 ) )
        ) - 1
      ) * 100
    int_gr[,t,"Intensity Growth|Final Energy|CO2-equiv (% pa)"] <-
      (
        (
          (tmp[,t,"Intensity|Final Energy|GHG (Mt CO2-equiv/EJ)"] / setYears(tmp[,(which(getYears(tmp)==t)-1),"Intensity|Final Energy|GHG (Mt CO2-equiv/EJ)"],t))
          ^ (1 / ( getYears(tmp[,t,],as.integer=TRUE) - getYears(tmp[,(which(getYears(tmp)==t)-1),],as.integer=TRUE) ) )
        ) - 1
      ) * 100
    int_gr[,t,"Intensity Growth|Final Energy|CO2-equiv to 2005 (% pa)"] <-
      (
        (
          (tmp[,t,"Intensity|Final Energy|GHG (Mt CO2-equiv/EJ)"] / setYears(tmp[,2005,"Intensity|Final Energy|GHG (Mt CO2-equiv/EJ)"],t))
          ^ (1 / ( getYears(tmp[,t,],as.integer = TRUE) - 2005 ) )
        ) - 1
      ) * 100
  }


  out <- mbind(tmp, int_gr)

  if ('subsectors' == module2realisation['industry',2]) {
    # add per-capita industry activity ----
    # find all activity variables
    foo <- grep('^(Production|Value Added)\\|Industry', getNames(output),
                value = TRUE)

    out <- mbind(
      out,

      # get activity data
      output[,,foo] %>%
        as.data.frame() %>%
        as_tibble() %>%
        select(-'Cell') %>%
        # join with population numbers
        left_join(
          output[,,'Population (million)'] %>%
            as.data.frame() %>%
            as_tibble() %>%
            select('Region', 'Year', population = 'Value'),

          c('Region', 'Year')
        ) %>%
        # join unit conversion
        extract(.data$Data1, c('variable', 'unit'), '^(.*) \\((.*)\\)$') %>%
        full_join(
          tribble(
            ~unit,                  ~new.unit,    ~factor,
            'Mt/yr',                't/yr',       1,
            'billion US$2017/yr',   'US$2017/yr', 1e-3),

          'unit'
        ) %>%
        assert(not_na, everything()) %>%
        # calculate
        mutate(Value = .data$Value / .data$population * .data$factor,
               !!sym(getSets(out, fulldim = FALSE)[3]) :=
                 paste0(.data$variable, '|per-capita (', .data$new.unit, ')')
        ) %>%
        # build magpie
        select('Region', 'Year', getSets(out, fulldim = FALSE)[3], 'Value') %>%
        `colnames<-`(c(getSets(out, fulldim = FALSE), 'Value')) %>%
        as.magpie(spatial = 1, temporal = 2, datacol = 4)
    )

    # add per-GDP industry activity ----
    out <- mbind(
      out,

      # get activity data
      output[,,foo] %>%
        as.data.frame() %>%
        as_tibble() %>%
        select(-'Cell') %>%
        # join with population numbers
        left_join(
          output[,,'GDP|PPP (billion US$2017/yr)'] %>%
            as.data.frame() %>%
            as_tibble() %>%
            select('Region', 'Year', population = 'Value'),

          c('Region', 'Year')
        ) %>%
        # join unit conversion
        extract(.data$Data1, c('variable', 'unit'), '^(.*) \\((.*)\\)$') %>%
        full_join(
          tribble(
            ~unit,                  ~new.unit,    ~factor,
            # Mt/$bn * 1e6 t/Mt * 1e-3 $bn/$m = t/$m
            'Mt/yr',                't/million US$2017',   1e3,
            'billion US$2017/yr',   'US$2017/US$2017',     1     # $bn/$bn = $/$
          ),

          'unit'
        ) %>%
        assert(not_na, everything()) %>%
        # calculate
        mutate(Value = .data$Value / .data$population * .data$factor,
               !!sym(getSets(out, fulldim = FALSE)[3]) :=
                 paste0(.data$variable, '|per-GDP (', .data$new.unit, ')')
        ) %>%
        # build magpie
        select('Region', 'Year', getSets(out, fulldim = FALSE)[3], 'Value') %>%
        `colnames<-`(c(getSets(out, fulldim = FALSE), 'Value')) %>%
        as.magpie(spatial = 1, temporal = 2, datacol = 4)
    )
  }

  # add adjusted electricity from coal and other fossils ----

  if (is.null(extraData)) {

    regionHash <- digest::digest(sort(readGDX(gdx, "all_regi")), "xxhash32")

    otherFossilsFile <- switch(regionHash,
                              "69585993" = "se_otherfoss_h12.cs4r",
                              "8c818b67" = "se_otherfoss_eu21.cs4r"
    )

    if (is.null(otherFossilsFile)) {
      stop("No file 'se_otherfoss.cs4r' found for regions in .gdx file.")
    }

    # download auxiliary file from RSE server
    f <- downloadAuxiliaryFile(otherFossilsFile)

    projections <- read.csv(f, sep = ",", skip = 4, header = FALSE) %>%
      as.magpie(temporal = 1, spatial = 2)

    if (!is.null(regionSubsetList)) {
      projections <- mbind(projections, calc_regionSubset_sums(projections, regionSubsetList))
    }

    unlink(f)

  } else {

    if (!file.exists(file.path(extraData, "se_otherfoss.cs4r"))) {
      stop("Auxiliary file 'se_otherfoss.cs4r' not found")
    }

    # read in projected electricity from waste and other fossils using energy demands from IEA Energy Balances.
    projections <- read.csv(
      file.path(extraData, "se_otherfoss.cs4r"),
      sep = ",", skip = 4, header = FALSE
    ) %>% as.magpie(temporal = 1, spatial = 2)

    if (!is.null(regionSubsetList)) {
      projections <- mbind(projections, calc_regionSubset_sums(projections, regionSubsetList))
    }

    # check if regional resolution matches
    if (length(setdiff(getItems(out, dim = 1), getItems(projections, dim = 1))) != 0 ||
        length(setdiff(getItems(projections, dim = 1), getItems(out, dim = 1))) != 0
    ) {
      stop("Regional resolution in 'se_otherfoss.cs4r' does not match.")
    }
  }

  y <- intersect(getYears(projections), getYears(out))
  out <- mbind(out, projections[, y, ])

  # SE|Electricity|Other Fossil|Other Fossil Adjusted = min(
  # SE|Electricity|Coal|w/o CC, SE|Electricity|Other Fossil|Projected);
  tmp <- mbind(
    output[, , "SE|Electricity|Coal|w/o CC (EJ/yr)"],
    out[, , "SE|Electricity|Other Fossil|Projected (EJ/yr)"]
  )
  tmp <- mcalc(tmp, `SE|Electricity|Other Fossil|Other Fossil Adjusted (EJ/yr)` ~
                 ifelse(`SE|Electricity|Coal|w/o CC (EJ/yr)` < `SE|Electricity|Other Fossil|Projected (EJ/yr)`,
                        `SE|Electricity|Coal|w/o CC (EJ/yr)`, `SE|Electricity|Other Fossil|Projected (EJ/yr)`
                 ),
               append = FALSE
  )
  out <- mbind(out, tmp)

  # SE|Electricity|Coal|w/o CC|Other Fossil Adjusted = SE|Electricity|Coal|w/o CC -
  # SE|Electricity|Other Fossil|Other Fossil Adjusted;
  tmp <- output[, , "SE|Electricity|Coal|w/o CC (EJ/yr)"] -
    out[, , "SE|Electricity|Other Fossil|Other Fossil Adjusted (EJ/yr)"]
  tmp[tmp < 0] <- 0
  tmp <- setItems(tmp, 3, "SE|Electricity|Coal|w/o CC|Other Fossil Adjusted (EJ/yr)")
  out <- mbind(out, tmp)

  # SE|Electricity|Coal|Other Fossil Adjusted = SE|Electricity|Coal -
  # SE|Electricity|Other Fossil|Other Fossil Adjusted;
  tmp <- output[, , "SE|Electricity|Coal (EJ/yr)"] -
    out[, , "SE|Electricity|Other Fossil|Other Fossil Adjusted (EJ/yr)"]
  tmp[tmp < 0] <- 0
  tmp <- setItems(tmp, 3, "SE|Electricity|Coal|Other Fossil Adjusted (EJ/yr)")
  out <- mbind(out, tmp)

  # OtherFossilShare =  SE|Electricity|Other Fossil|Other Fossil Adjusted /
  # SE|Electricity|Coal|w/o CC;
  share <- out[, , "SE|Electricity|Other Fossil|Other Fossil Adjusted (EJ/yr)"] /
    output[, , "SE|Electricity|Coal|w/o CC (EJ/yr)"]
  share[is.na(share)] <- 0
  share <- setItems(share, 3, "OtherFossilShare")

  # Cap|Electricity|Other Fossil|Other Fossil Adjusted = Cap|Electricity|Coal|w/o CC * OtherFossilShare;
  tmp <- output[, , "Cap|Electricity|Coal|w/o CC (GW)"] * share
  tmp <- setItems(tmp, 3, "Cap|Electricity|Other Fossil|Other Fossil Adjusted (GW)")
  out <- mbind(out, tmp)

  # Cap|Electricity|Coal|w/o CC|Other Fossil Adjusted = Cap|Electricity|Coal|w/o CC -
  # Cap|Electricity|Other Fossil|Other Fossil Adjusted;
  tmp <- output[, , "Cap|Electricity|Coal|w/o CC (GW)"] -
    out[, , "Cap|Electricity|Other Fossil|Other Fossil Adjusted (GW)"]
  tmp <- setItems(tmp, 3, "Cap|Electricity|Coal|w/o CC|Other Fossil Adjusted (GW)")
  out <- mbind(out, tmp)

  # Cap|Electricity|Coal|Other Fossil Adjusted = Cap|Electricity|Coal -
  # Cap|Electricity|Other Fossil|Other Fossil Adjusted;
  tmp <- output[, , "Cap|Electricity|Coal (GW)"] -
    out[, , "Cap|Electricity|Other Fossil|Other Fossil Adjusted (GW)"]
  tmp <- setItems(tmp, 3, "Cap|Electricity|Coal|Other Fossil Adjusted (GW)")
  out <- mbind(out, tmp)

  getSets(out)[3] <- "variable"
  return(out)
}
